apiVersion: v1
kind: Service
metadata:
  name: eshop
  labels:
    app: eshop
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: eshop
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: eshop
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: eshop
---
apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    app: eshop
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: eshop
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: eshop
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: eshop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop
        version: v1
    spec:
      containers:
      - name: eshop
        image: zhaohuabing/istio-opentracing-demo:1.0
        ports:
        - containerPort: 8080